### ISSUE TITLE
Eagle files

### ISSUE THREAD

**Issue by fancnc** [WickedDevice/AngularClock#2]
The board and schematic files get following error when trying to load into Eagle version 9.6.2

Loading D:/Analog clock/angularclock.sch ...

Error:

line 8, column 88: This is not an EAGLE file.

**Comment by vicatcu** [comment]
Hi! Thanks for reaching out, the designs come from Eagle 7. You should be able to get older versions of Eagle from the Autocad archives here: http://eagle.autodesk.com/eagle/software-versions.

**Comment by fancnc** [comment]
Thanks Victor, much appreciated.  Sent from Mail for Windows From: Victor ApreaSent: Thursday, March 24, 2022 5:18 PMTo: WickedDevice/AngularClockCc: fancnc; AuthorSubject: Re: [WickedDevice/AngularClock] Eagle files (Issue #2) Hi! Thanks for reaching out, the designs come from Eagle 7. You should be able to get older versions of Eagle from the Autocad archives here: http://eagle.autodesk.com/eagle/software-versions.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
